import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { CONFIG, BACKEND_CONFIGURED } from "../config.js";

const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let supabase=null,session=null,igdbResults=[];
const repRank=s=>s<0?"☠️ Traître":s<20?"👤 Inconnu":s<50?"🏠 Habitué":s<80?"🗣️ Conseiller":s<100?"⚜️ Confident":"👑 Favori";
function toast(message){const e=document.createElement("div");e.textContent=message;Object.assign(e.style,{position:"fixed",right:"20px",bottom:"20px",zIndex:999,padding:"12px 16px",background:"#0b0909",border:"1px solid rgba(183,147,100,.35)",color:"#eadfce"});document.body.appendChild(e);setTimeout(()=>e.remove(),3000)}
async function signIn(){if(!supabase)return;await supabase.auth.signInWithOAuth({provider:"twitch",options:{redirectTo:location.href}})}
async function checkAccess(){
  if(!session?.user){$("#admin-login").classList.remove("hidden");$("#admin-logout").classList.add("hidden");$("#admin-gate").classList.remove("hidden");$("#admin-app").classList.add("hidden");$("#admin-gate-message").textContent="Connexion Twitch nécessaire.";return}
  $("#admin-login").classList.add("hidden");$("#admin-logout").classList.remove("hidden");const{data:isAdmin,error}=await supabase.rpc("current_is_admin");
  if(error||!isAdmin){$("#admin-gate").classList.remove("hidden");$("#admin-app").classList.add("hidden");$("#admin-gate-message").textContent="Ce compte Twitch n’a pas les droits d’administration.";return}
  $("#admin-gate").classList.add("hidden");$("#admin-app").classList.remove("hidden");await refreshAll()
}
async function boot(){
  if(!BACKEND_CONFIGURED){$("#admin-gate-message").textContent="Le backend Supabase n’est pas encore configuré dans config.js.";return}
  supabase=createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,detectSessionInUrl:true}});const{data}=await supabase.auth.getSession();session=data.session;await checkAccess();supabase.auth.onAuthStateChange(async(_e,s)=>{session=s;await checkAccess()})
}
async function refreshAll(){await Promise.all([loadStats(),loadSuggestions(),loadLibrary(),loadPolls(),loadReputation(),loadCollaborators()])}
async function loadStats(){
  const[{data:s},{data:g},{data:p},{data:r},{data:c}]=await Promise.all([
    supabase.from("suggestions").select("status"),supabase.from("library_games").select("id"),supabase.from("polls").select("id").eq("is_active",true),supabase.from("reputation_scores").select("id"),supabase.from("collaborators").select("id").eq("active",true)
  ]);
  $("#stat-new-suggestions").textContent=(s||[]).filter(x=>x.status==="new").length;$("#stat-considering").textContent=(s||[]).filter(x=>x.status==="considering").length;$("#stat-library").textContent=(g||[]).length;$("#stat-polls").textContent=(p||[]).length;$("#stat-reputation").textContent=(r||[]).length;$("#stat-collaborators").textContent=(c||[]).length
}
async function loadSuggestions(){
  const{data,error}=await supabase.from("suggestions").select("*,profiles!suggestions_author_id_fkey(display_name,avatar_url)").order("created_at",{ascending:false});if(error){$("#admin-suggestions").textContent=error.message;return}
  const all=data||[];$("#admin-suggestions").innerHTML=all.map(s=>`<article class="admin-item" data-suggestion="${s.id}"><div class="admin-item-head"><div><small>${esc(s.profiles?.display_name||"Viewer")} · ${esc(s.category)}</small><h2>${esc(s.title)}</h2></div><label>Épinglée <input class="suggestion-pinned" type="checkbox" ${s.pinned?"checked":""}></label></div><p>${esc(s.body)}</p><div class="admin-two-cols"><label>Statut<select class="suggestion-status">${["new","considering","planned","completed","rejected","archived"].map(st=>`<option value="${st}" ${s.status===st?"selected":""}>${st}</option>`).join("")}</select></label><label>Fusionner vers<select class="suggestion-merge"><option value="">—</option>${all.filter(x=>x.id!==s.id).map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join("")}</select></label></div><label>Réponse officielle<textarea class="suggestion-reply" rows="3">${esc(s.official_reply||"")}</textarea></label><div class="admin-actions"><button data-save-suggestion="${s.id}">Enregistrer</button><button data-merge-suggestion="${s.id}">Fusionner</button><button data-link-game="${s.id}">Ajouter un jeu lié</button><button data-delete-suggestion="${s.id}">Supprimer</button></div></article>`).join("");
  $$('[data-save-suggestion]').forEach(b=>b.onclick=()=>saveSuggestion(b.dataset.saveSuggestion));$$('[data-merge-suggestion]').forEach(b=>b.onclick=()=>mergeSuggestion(b.dataset.mergeSuggestion));$$('[data-delete-suggestion]').forEach(b=>b.onclick=()=>deleteSuggestion(b.dataset.deleteSuggestion));$$('[data-link-game]').forEach(b=>b.onclick=()=>{const item=$(`[data-suggestion="${b.dataset.linkGame}"]`);$("#game-search-input").value=$("h2",item).textContent;document.querySelector('[data-admin-tab="library"]').click();searchGames(b.dataset.linkGame)})
}
async function saveSuggestion(id){const item=$(`[data-suggestion="${id}"]`),status=$(".suggestion-status",item).value,official_reply=$(".suggestion-reply",item).value.trim()||null,pinned=$(".suggestion-pinned",item).checked;const{error}=await supabase.from("suggestions").update({status,official_reply,pinned}).eq("id",id);if(error)toast(error.message);else{toast("Suggestion mise à jour.");await refreshAll()}}
async function mergeSuggestion(source){const item=$(`[data-suggestion="${source}"]`),target=$(".suggestion-merge",item).value;if(!target)return toast("Choisis une suggestion cible.");if(!confirm("Fusionner cette suggestion et transférer ses votes ?"))return;const{error}=await supabase.rpc("merge_suggestions",{p_source:source,p_target:target});if(error)toast(error.message);else{toast("Suggestions fusionnées.");await refreshAll()}}
async function deleteSuggestion(id){if(!confirm("Supprimer définitivement cette suggestion ?"))return;const{error}=await supabase.from("suggestions").delete().eq("id",id);if(error)toast(error.message);else await refreshAll()}
async function searchGames(sourceSuggestionId=null){const q=$("#game-search-input").value.trim();if(q.length<2)return;$("#game-search-results").innerHTML="Recherche…";const{data,error}=await supabase.functions.invoke("game-search",{body:{query:q}});if(error){$("#game-search-results").textContent=error.message;return}igdbResults=(data?.games||[]).map(g=>({...g,sourceSuggestionId}));$("#game-search-results").innerHTML=igdbResults.map((g,i)=>`<article class="game-search-card">${g.cover_url?`<img src="${esc(g.cover_url)}" alt="">`:""}<strong>${esc(g.name)}</strong><small>${g.release_year||""}</small><button data-add-game="${i}">Ajouter</button></article>`).join("");$$('[data-add-game]').forEach(b=>b.onclick=()=>addGame(Number(b.dataset.addGame)))}
async function addGame(i){const g=igdbResults[i],status=prompt("Statut : playing, backlog, completed, wishlist, paused ou abandoned","wishlist")||"wishlist",streamed=confirm("Ce jeu a-t-il déjà été streamé ?");const{error}=await supabase.from("library_games").insert({igdb_id:g.id,name:g.name,slug:g.slug,cover_url:g.cover_url||null,genres:g.genres||[],platforms:g.platforms||[],release_date:g.release_date||null,status,streamed,source_suggestion_id:g.sourceSuggestionId||null});if(error)toast(error.message);else{toast("Jeu ajouté.");await refreshAll()}}
async function loadLibrary(){const{data,error}=await supabase.from("library_games").select("*").order("updated_at",{ascending:false});if(error){$("#admin-library").textContent=error.message;return}$("#admin-library").innerHTML=(data||[]).map(g=>`<article class="admin-item" data-game="${g.id}"><div class="admin-item-head"><h2>${esc(g.name)}</h2><small>${g.streamed?"🎥 Streamé":""}</small></div><div class="admin-two-cols"><label>Statut<select class="game-status">${["playing","backlog","completed","wishlist","paused","abandoned"].map(st=>`<option ${g.status===st?"selected":""}>${st}</option>`).join("")}</select></label><label class="check-row"><input class="game-streamed" type="checkbox" ${g.streamed?"checked":""}> Streamé sur la chaîne</label></div><label>Note personnelle<textarea class="game-note" rows="2">${esc(g.personal_note||"")}</textarea></label><div class="admin-actions"><button data-save-game="${g.id}">Enregistrer</button><button data-delete-game="${g.id}">Supprimer</button></div></article>`).join("");$$('[data-save-game]').forEach(b=>b.onclick=()=>saveGame(b.dataset.saveGame));$$('[data-delete-game]').forEach(b=>b.onclick=()=>deleteGame(b.dataset.deleteGame))}
async function saveGame(id){const item=$(`[data-game="${id}"]`),status=$(".game-status",item).value,streamed=$(".game-streamed",item).checked,personal_note=$(".game-note",item).value.trim()||null;const{error}=await supabase.from("library_games").update({status,streamed,personal_note}).eq("id",id);if(error)toast(error.message);else{toast("Jeu mis à jour.");await refreshAll()}}
async function deleteGame(id){if(!confirm("Supprimer ce jeu de la ludothèque ?"))return;await supabase.from("library_games").delete().eq("id",id);await refreshAll()}
async function createPoll(e){e.preventDefault();const title=$("#poll-title").value.trim(),description=$("#poll-description").value.trim()||null,labels=$("#poll-options").value.split("\n").map(x=>x.trim()).filter(Boolean);if(labels.length<2)return toast("Il faut au moins deux options.");const endsAt=$("#poll-end").value?new Date($("#poll-end").value).toISOString():null;const{data:poll,error}=await supabase.from("polls").insert({title,description,allow_multiple:$("#poll-multiple").checked,results_visibility:$("#poll-visibility").value,ends_at:endsAt,created_by:session.user.id}).select().single();if(error)return toast(error.message);const{error:oe}=await supabase.from("poll_options").insert(labels.map((label,position)=>({poll_id:poll.id,label,position})));if(oe)toast(oe.message);else{$("#poll-form").reset();toast("Sondage créé.");await refreshAll()}}
async function loadPolls(){const{data,error}=await supabase.from("polls").select("*,poll_options(*)").order("created_at",{ascending:false});if(error){$("#admin-polls").textContent=error.message;return}$("#admin-polls").innerHTML=(data||[]).map(p=>`<article class="admin-item" data-poll="${p.id}"><div class="admin-item-head"><h2>${esc(p.title)}</h2><small>${p.is_active?"Actif":"Fermé"}</small></div><p>${(p.poll_options||[]).map(o=>esc(o.label)).join(" · ")}</p><div class="admin-actions"><button data-toggle-poll="${p.id}">${p.is_active?"Fermer":"Rouvrir"}</button><button data-delete-poll="${p.id}">Supprimer</button></div></article>`).join("");$$('[data-toggle-poll]').forEach(b=>b.onclick=()=>togglePoll(b.dataset.togglePoll));$$('[data-delete-poll]').forEach(b=>b.onclick=()=>deletePoll(b.dataset.deletePoll))}
async function togglePoll(id){const item=$(`[data-poll="${id}"]`),active=$("small",item).textContent==="Actif";await supabase.from("polls").update({is_active:!active}).eq("id",id);await refreshAll()}
async function deletePoll(id){if(!confirm("Supprimer ce sondage ?"))return;await supabase.from("polls").delete().eq("id",id);await refreshAll()}

async function loadReputation(){
  const{data,error}=await supabase.from("reputation_scores").select("*").order("score",{ascending:false});if(error){$("#admin-reputation").textContent=error.message;return}
  const rows=data||[];$("#admin-reputation").innerHTML=rows.length?rows.map(r=>`<article class="admin-item"><div class="admin-item-head"><div><small>${esc(r.twitch_login||"")}</small><h2>${esc(r.display_name||r.twitch_login||"Viewer")}</h2></div><span class="score-pill">${r.score>0?"+":""}${r.score}</span></div><div class="admin-meta-line"><span>${esc(repRank(r.score))}</span><span>Dernière synchro : ${new Date(r.updated_at).toLocaleString("fr-FR")}</span>${r.twitch_user_id?`<span>ID Twitch : ${esc(r.twitch_user_id)}</span>`:""}</div></article>`).join(""):`<div class="admin-card"><p>Aucun score synchronisé pour le moment.</p></div>`
}

async function createCollaborator(e){
  e.preventDefault();const twitch_login=$("#collaborator-login").value.trim().toLowerCase(),description=$("#collaborator-description").value.trim()||null,sort_order=Number($("#collaborator-order").value||0);if(!twitch_login)return;
  const{error}=await supabase.from("collaborators").insert({twitch_login,description,sort_order,active:true});if(error)toast(error.message);else{$("#collaborator-form").reset();$("#collaborator-order").value="0";toast("Collaborateur ajouté.");await refreshAll()}
}
async function loadCollaborators(){
  const{data,error}=await supabase.from("collaborators").select("*").order("sort_order",{ascending:true}).order("created_at",{ascending:true});if(error){$("#admin-collaborators").textContent=error.message;return}
  $("#admin-collaborators").innerHTML=(data||[]).map(c=>`<article class="admin-item" data-collaborator="${c.id}"><div class="admin-item-head"><div><small>twitch.tv/${esc(c.twitch_login)}</small><h2>${esc(c.twitch_login)}</h2></div><label class="check-row"><input class="collab-active" type="checkbox" ${c.active?"checked":""}> Actif</label></div><div class="admin-two-cols"><label>Login Twitch<input class="collab-login" value="${esc(c.twitch_login)}"></label><label>Ordre<input class="collab-order" type="number" value="${Number(c.sort_order||0)}"></label></div><label>Description<textarea class="collab-description" rows="3">${esc(c.description||"")}</textarea></label><div class="admin-actions"><button data-save-collab="${c.id}">Enregistrer</button><button data-delete-collab="${c.id}">Supprimer</button></div></article>`).join("");$$('[data-save-collab]').forEach(b=>b.onclick=()=>saveCollaborator(b.dataset.saveCollab));$$('[data-delete-collab]').forEach(b=>b.onclick=()=>deleteCollaborator(b.dataset.deleteCollab))
}
async function saveCollaborator(id){const item=$(`[data-collaborator="${id}"]`),twitch_login=$(".collab-login",item).value.trim().toLowerCase(),description=$(".collab-description",item).value.trim()||null,sort_order=Number($(".collab-order",item).value||0),active=$(".collab-active",item).checked;const{error}=await supabase.from("collaborators").update({twitch_login,description,sort_order,active}).eq("id",id);if(error)toast(error.message);else{toast("Collaborateur mis à jour.");await refreshAll()}}
async function deleteCollaborator(id){if(!confirm("Retirer ce collaborateur du site ?"))return;const{error}=await supabase.from("collaborators").delete().eq("id",id);if(error)toast(error.message);else await refreshAll()}

$$('[data-admin-tab]').forEach(btn=>btn.onclick=()=>{$$('[data-admin-tab]').forEach(b=>b.classList.remove("active"));btn.classList.add("active");$$('[data-admin-panel]').forEach(p=>p.classList.toggle("hidden",p.dataset.adminPanel!==btn.dataset.adminTab))});
$("#admin-login").onclick=signIn;$("#admin-logout").onclick=async()=>{await supabase.auth.signOut();location.reload()};$("#game-search-button").onclick=()=>searchGames();$("#game-search-input").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();searchGames()}});$("#poll-form").addEventListener("submit",createPoll);$("#collaborator-form").addEventListener("submit",createCollaborator);boot();
