import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.4/+esm";
import { CONFIG, BACKEND_CONFIGURED } from "../config.js";

const $=(s,c=document)=>c.querySelector(s);
const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const diploTypes=['diplomatie','congrès','traité','déclaration','correspondance'];
const db=BACKEND_CONFIGURED?createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,detectSessionInUrl:false}}):null;
let participants=[],chapters=[];

function toast(message){const e=document.createElement('div');e.className='admin-toast';e.textContent=message;document.body.appendChild(e);setTimeout(()=>e.remove(),3200)}
function eventId(){return $('#event-admin-select')?.value||null}
function cleanFileName(name='file'){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').slice(-120)}
function mediaTypeFromFile(file){if(file?.type.startsWith('image/'))return'image';if(file?.type.startsWith('audio/'))return'audio';if(file?.type.startsWith('video/'))return'video';return'link'}
async function uploadFile(file,prefix='media'){
  const id=eventId();if(!id||!file)throw new Error('Événement ou fichier manquant.');
  if(file.size>50*1024*1024)throw new Error('Le fichier dépasse la limite de 50 Mo.');
  const path=`${id}/${prefix}-${Date.now()}-${cleanFileName(file.name)}`;
  const{error}=await db.storage.from('event-media').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||undefined});
  if(error)throw error;
  const{data}=db.storage.from('event-media').getPublicUrl(path);return{path,url:data.publicUrl};
}
function refreshLegacy(){const s=$('#event-admin-select');if(s)s.dispatchEvent(new Event('change',{bubbles:true}))}
function setLabelText(label,text){if(!label)return;const n=[...label.childNodes].find(x=>x.nodeType===Node.TEXT_NODE&&x.textContent.trim());if(n)n.textContent=text;}
function polishLegacyAdmin(){
  $$('#event-entries-admin .event-entry-admin').forEach(card=>{const type=$('.event-entry-type-edit',card)?.value||'';card.classList.toggle('v51-diplomacy-hidden',diploTypes.includes(type));const pub=$('.event-entry-public-edit',card)?.closest('label');if(pub)pub.style.display='none';const feat=$('.event-entry-featured-edit',card)?.closest('label');if(feat)feat.style.display='none';setLabelText($('.event-entry-chapter-edit',card)?.closest('label'),'Période');setLabelText($('.event-entry-date-edit',card)?.closest('label'),'Date / repère');const review=$('.event-entry-review-edit',card);if(review){setLabelText(review.closest('label'),'Publication');const labels={needs_review:'Brouillon',approved:'Publié',rejected:'Masqué'};[...review.options].forEach(o=>o.textContent=labels[o.value]||o.textContent)}});
  $$('#event-chapters-admin .event-chapter-admin').forEach(card=>{const lab=$('.event-chapter-public',card)?.closest('label');if(lab)setLabelText(lab,'Afficher sur la frise')});
  $$('#event-media-admin .event-media-admin-row').forEach(card=>{const feat=$('.event-media-featured-edit',card)?.closest('label');if(feat)feat.style.display='none';const pub=$('.event-media-public-edit',card)?.closest('label');if(pub)setLabelText(pub,'Afficher sur le site')});
}
function participantOptions(selected=''){return `<option value="">— Choisir un pays —</option>${participants.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(p.title)} · ${esc(p.player_name||p.participant_key)}</option>`).join('')}`}
function chapterOptions(selected=''){return `<option value="">— Choisir une période —</option>${chapters.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.title)}</option>`).join('')}`}
async function loadDeclarationAdmin(){
  const id=eventId(),box=$('#event-declarations-admin');if(!id||!box||!db)return;
  const [pr,ch,en]=await Promise.all([db.from('site_event_participants').select('*').eq('event_id',id).order('sort_order'),db.from('site_event_chapters').select('*').eq('event_id',id).order('sort_order'),db.from('site_event_entries').select('*').eq('event_id',id).in('entry_type',diploTypes).order('created_at')]);
  participants=pr.data||[];chapters=ch.data||[];$('#event-declaration-country').innerHTML=participantOptions();$('#event-declaration-chapter').innerHTML=chapterOptions();
  const rows=en.data||[];box.innerHTML=rows.length?rows.map(e=>{const p=participants.find(x=>x.id===e.participant_id);return `<article class="admin-item event-declaration-admin" data-declaration-id="${e.id}"><div class="admin-item-head"><div><small>${p?esc(p.title):'Pays à préciser'} · ${esc(e.entry_type)}</small><h2>${esc(e.title)}</h2></div><span class="event-public-state ${e.public?'is-public':'is-draft'}">${e.public?'Publié':'Brouillon'}</span></div><div class="admin-three-cols"><label>Pays<select class="v51-country">${participantOptions(e.participant_id||'')}</select></label><label>Période<select class="v51-chapter">${chapterOptions(e.chapter_id||'')}</select></label><label>Type<select class="v51-type"><option value="déclaration" ${e.entry_type==='déclaration'?'selected':''}>Déclaration publique</option><option value="traité" ${e.entry_type==='traité'?'selected':''}>Traité</option><option value="congrès" ${e.entry_type==='congrès'?'selected':''}>Congrès</option><option value="correspondance" ${e.entry_type==='correspondance'?'selected':''}>Correspondance</option><option value="diplomatie" ${e.entry_type==='diplomatie'?'selected':''}>Autre diplomatie</option></select></label></div><label>Titre<input class="v51-title" value="${esc(e.title)}"></label><label>Texte<textarea class="v51-body" rows="5">${esc(e.body||e.summary||'')}</textarea></label><label class="check-row"><input class="v51-public" type="checkbox" ${e.public?'checked':''}> Afficher sur le site</label><div class="admin-actions"><button type="button" data-v51-save-declaration="${e.id}">Enregistrer</button><button type="button" class="danger-action" data-v51-delete-declaration="${e.id}">Supprimer</button></div></article>`}).join(''):'<p>Aucune déclaration diplomatique pour le moment.</p>';
}
async function saveDeclaration(id){const el=$(`[data-declaration-id="${id}"]`);if(!el)return;const body=$('.v51-body',el).value.trim(),pub=$('.v51-public',el).checked;const payload={participant_id:$('.v51-country',el).value||null,chapter_id:$('.v51-chapter',el).value||null,entry_type:$('.v51-type',el).value,title:$('.v51-title',el).value.trim(),summary:body.slice(0,420)||null,body:body||null,review_status:pub?'approved':'needs_review',public:pub};const{error}=await db.from('site_event_entries').update(payload).eq('id',id);if(error)toast(error.message);else{toast('Déclaration enregistrée.');await loadDeclarationAdmin();refreshLegacy()}}
async function deleteDeclaration(id){if(!confirm('Supprimer cette déclaration ?'))return;const{error}=await db.from('site_event_entries').delete().eq('id',id);if(error)toast(error.message);else{toast('Déclaration supprimée.');await loadDeclarationAdmin();refreshLegacy()}}
$('#event-declaration-form')?.addEventListener('submit',async e=>{e.preventDefault();const id=eventId();if(!id)return;const body=$('#event-declaration-body').value.trim(),pub=$('#event-declaration-public').checked;const payload={event_id:id,participant_id:$('#event-declaration-country').value||null,chapter_id:$('#event-declaration-chapter').value||null,entry_type:$('#event-declaration-type').value,title:$('#event-declaration-title').value.trim(),summary:body.slice(0,420)||null,body,source_type:'manual_rp',importance:'major',review_status:pub?'approved':'needs_review',public:pub,sort_order:600};const{error}=await db.from('site_event_entries').insert(payload);if(error)toast(error.message);else{e.target.reset();$('#event-declaration-public').checked=true;toast('Déclaration ajoutée.');await loadDeclarationAdmin();refreshLegacy()}});
document.addEventListener('click',async e=>{const save=e.target.closest('[data-v51-save-declaration]');if(save){await saveDeclaration(save.dataset.v51SaveDeclaration);return}const del=e.target.closest('[data-v51-delete-declaration]');if(del){await deleteDeclaration(del.dataset.v51DeleteDeclaration);return}},true);
$('#event-media-form')?.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const id=eventId();if(!id)return;const file=$('#event-media-file')?.files?.[0],external=$('#event-media-url').value.trim(),selected=$('#event-media-type').value;if(!file&&!external){toast('Choisis un fichier ou renseigne une URL.');return}try{let url=external,storage_path=null,type=selected==='auto'?(file?mediaTypeFromFile(file):'link'):selected;if(file){const uploaded=await uploadFile(file,'media');url=uploaded.url;storage_path=uploaded.path;if(selected==='auto')type=mediaTypeFromFile(file)}const{error}=await db.from('site_event_media').insert({event_id:id,media_type:type,title:$('#event-media-title').value.trim()||file?.name||null,caption:$('#event-media-caption').value.trim()||null,url,storage_path,public:$('#event-media-public').checked,featured:false,sort_order:0});if(error)throw error;e.target.reset();$('#event-media-public').checked=true;toast('Média ajouté.');refreshLegacy()}catch(err){toast(err.message||'Impossible d’ajouter le média.')}},{capture:true});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-delete-event-media]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(!confirm('Supprimer ce média ?'))return;const id=b.dataset.deleteEventMedia;const{data:row}=await db.from('site_event_media').select('storage_path').eq('id',id).maybeSingle();if(row?.storage_path)await db.storage.from('event-media').remove([row.storage_path]);const{error}=await db.from('site_event_media').delete().eq('id',id);if(error)toast(error.message);else{toast('Média supprimé.');refreshLegacy()}},true);
$('#event-general-form')?.addEventListener('submit',async e=>{const file=$('#event-hero-file')?.files?.[0];if(!file)return;e.preventDefault();e.stopImmediatePropagation();try{const uploaded=await uploadFile(file,'hero');const id=eventId();const featured=$('#event-featured-input').checked;if(featured)await db.from('site_events').update({featured:false}).neq('id',id);const next=$('#event-next-session-input').value;const{error}=await db.from('site_events').update({title:$('#event-title-input').value.trim(),subtitle:$('#event-subtitle-input').value.trim()||null,summary:$('#event-summary-input').value.trim()||null,status:$('#event-status-input').value,featured,world_current_date:$('#event-world-current-input').value||null,public_snapshot_date:$('#event-public-snapshot-input').value||null,public_chronicle_cutoff_date:$('#event-cutoff-input').value||null,next_session_at:next?new Date(next).toISOString():null,hero_image_url:uploaded.url,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;toast('Présentation et image enregistrées.');refreshLegacy()}catch(err){toast(err.message||'Impossible d’envoyer l’image.')}},{capture:true});
const observer=new MutationObserver(()=>{polishLegacyAdmin();loadDeclarationAdmin().catch(()=>{})});const entries=$('#event-entries-admin');if(entries)observer.observe(entries,{childList:true,subtree:true});const media=$('#event-media-admin');if(media)observer.observe(media,{childList:true,subtree:true});$('#event-admin-select')?.addEventListener('change',()=>setTimeout(()=>{polishLegacyAdmin();loadDeclarationAdmin()},80));setTimeout(()=>{polishLegacyAdmin();loadDeclarationAdmin().catch(()=>{})},900);
